[package]
name = "j"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", features = ["nightly", "metal"]}#, features = ["nightly", "vulkan"] }
serde = "*"
tiled = {path = "../rs-tiled", features=["amethyst"]}
